# Generated by Django 2.2 on 2019-11-29 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 17, 25, 30, 909030)),
            preserve_default=False,
        ),
    ]
