# Generated by Django 2.2 on 2019-12-02 17:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20191202_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
