# Generated by Django 2.2 on 2019-12-04 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_client_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 12, 4, 13, 20, 57, 161783)),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Sex'), ('M', 'MAN'), ('W', 'WOMAN')], max_length=1, null=True),
        ),
    ]
