# Generated by Django 2.2 on 2020-01-11 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20200111_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 11, 12, 41, 3, 906360, tzinfo=utc), null=True),
        ),
    ]
