# Generated by Django 2.2 on 2020-01-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20200111_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMedia',
            new_name='Social',
        ),
    ]
