# Generated by Django 2.2 on 2020-01-11 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20200111_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='SocialMedia',
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
