# Generated by Django 2.2 on 2020-01-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20200111_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
