# Generated by Django 2.2 on 2020-02-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20200229_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.ImageField(default='/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=models.ImageField(default='/default.jpg', upload_to=''),
        ),
    ]
